# TEMPLATE

## :fire: Do not edit this file - copy the template and create your own file.

**[Step-By-Step Technical Blog Guide](https://hq.bitproject.org/how-to-write-a-technical-blog/)**

### :pushpin: Step 1
**TITLE:**    
Web-Scraping-Current-Stock-Price

**TOPIC:**    
Machine Learning

**DESCRIPTION (5-7+ sentences):**    
The topic that I decided to focus on is web scraping of stock prices. This means that whenever a stock price changes, the program will have the functionality of outputting that information. The flexibility and simplicity of this program that I implemented is evident of how easy web scraping is to learn and how accessible it is to anyone that has a computer and an IDE. Anyone can learn how to web scrape and this is at its most basic form. Web scraping has been something that I've been wanting to learn for awhile now, so this was the perfect opportunity for me to learn and educate others on what I learned throughout this process. 

### :pushpin: Step 2
:family: **TARGET AUDIENCE (3-5+ sentences):**    
Beginning Programmers with minimal knowledge in coding

### :pushpin: Step 3
> Outline your learning/teaching structure: 
My teaching structure is straight to the point and step by step. I don't want to bore those that don't want to read a full essay about a simple topic. Especially in this generation, people hate reading, so I think including images and getting straight to the point will be quickest and easiest to learn. 

**Beginning (2-3+ sentences):**    
I will discuss about my motive for creating the blog. Out of all the ideas that I could've chosen, why did I choose this one? Unrelated to my motive, I will transition into talking about the modules necessary to be imported and installed on your operating system for this program to work.

**Middle (2-3+ sentences):**    
I will discuss about how to actually implement the program. Each code will be explained concisely. I have about 10-15 lines of code intended to be explained, so I don't want to include paragraphs about each line of code when some of it is self explanatory. 

**End (2-3+ sentences):**    
Lastly, I will talk about how this topic relates to the real world and why it is relevant in the society that we live in today. I will also provide screenshots of what the output looks like and provide an ending statement to encourage others to pursue more web scraping! 
